"""Storage schema for the labelling pipeline.

Separate SQLite file from assistant.db on purpose: the behavioural store gets
wiped and regenerated by sync, and labels are expensive human input that has to
survive that. Different lifetimes, different files.

Notes:
 - candidates holds every decision, fired or not, plus the reason it wasn't
   fired. You can't sample "suppressed by cooldown" as a stratum unless you
   recorded that the cooldown was what suppressed it.
 - items.inclusion_prob isn't bookkeeping, every metric divides by it. Lose it
   and the labels are unusable because the sample is stratified.
 - responses keeps the raw answers next to the derived label. Derivations change,
   what someone actually said doesn't.
"""

from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

UTC = timezone.utc

DB_PATH = os.environ.get(
    "PROACT_LABELS_DB", os.path.join(os.path.dirname(__file__), "labels.db")
)


@contextmanager
def get_db(path: str | None = None):
    conn = sqlite3.connect(path or DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Strata
# ---------------------------------------------------------------------------
# Six strata, chosen so that every reason a notification did or did not happen is
# separately observable. S3-S6 exist purely so recall is measurable; a dataset
# built only from S1/S2 can report precision and nothing else.
STRATA = (
    "S1_FIRED_STRONG",    # production fired, confidence comfortably over threshold
    "S2_FIRED_SOFT",      # production fired on the soft/low-confidence tier
    "S3_NEARMISS",        # not fired: confidence just below threshold
    "S4_COOLDOWN",        # not fired: suppressed by a cooldown window
    "S5_SUPPRESSED",      # not fired: dismissal history, or user already acted
    "S6_CONTROL",         # no candidate at all, a random window with no pattern
)

FIRED_STRATA = {"S1_FIRED_STRONG", "S2_FIRED_SOFT"}


# ---------------------------------------------------------------------------
# Row types
# ---------------------------------------------------------------------------
@dataclass
class Candidate:
    """One decision at one tick, as observed in shadow mode."""

    participant_id: str
    domain: str                 # "ride" | "food"
    decided_at: str             # ISO8601, the simulated/real tick time
    stratum: str
    fired_prod: bool            # would the PRODUCTION policy have notified?
    reason: str                 # verdict reason ("fire", "cooldown:ride:45m", ...)
    confidence: float
    threshold: float
    pattern_ref: str = ""
    context_json: str = "{}"    # what the suggestion would have said
    candidate_id: int | None = None


@dataclass
class Batch:
    """A set of items sent to one participant as one form."""

    participant_id: str
    kind: str                   # "ema" (single item, in the moment) | "daily"
    created_at: str
    token: str                  # HMAC-signed, tamper-evident
    expires_at: str
    form_id: str = ""
    sent_at: str = ""
    batch_id: int | None = None


@dataclass
class Item:
    """A candidate selected into a batch, with the probability it was selected."""

    batch_id: int
    candidate_id: int
    stratum: str
    inclusion_prob: float       # pi_s, REQUIRED for unbiased estimation
    position: int               # order shown, so order effects are measurable
    is_gold: bool = False       # answer known from the log; an attention check
    gold_expected: str = ""
    item_id: int | None = None


@dataclass
class Response:
    """What the participant actually said."""

    item_id: int
    # The label that is NOT recoverable from behavioural data:
    welcome: str = ""           # "useful" | "neutral" | "annoying"
    # Intent at the time, lets non-fired strata yield false negatives:
    wanted: str = ""            # "yes" | "no" | "dont_remember"
    # Verifiable against the order log -> a label-quality signal, not a label:
    did_act: str = ""           # "yes" | "no" | "dont_remember"
    answered_at: str = ""
    latency_ms: int = 0         # straightlining detector
    raw_json: str = "{}"
    response_id: int | None = None


@dataclass
class Participant:
    participant_id: str
    consented_at: str
    timezone: str = "Asia/Kolkata"
    status: str = "active"      # active | withdrawn
    notes: str = ""


# ---------------------------------------------------------------------------
# DDL
# ---------------------------------------------------------------------------
DDL = """
CREATE TABLE IF NOT EXISTS participants (
    participant_id TEXT PRIMARY KEY,
    consented_at   TEXT NOT NULL,
    timezone       TEXT NOT NULL DEFAULT 'Asia/Kolkata',
    status         TEXT NOT NULL DEFAULT 'active',
    notes          TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS candidates (
    candidate_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    participant_id TEXT NOT NULL REFERENCES participants(participant_id),
    domain         TEXT NOT NULL,
    decided_at     TEXT NOT NULL,
    stratum        TEXT NOT NULL,
    fired_prod     INTEGER NOT NULL,
    reason         TEXT NOT NULL,
    confidence     REAL NOT NULL,
    threshold      REAL NOT NULL,
    pattern_ref    TEXT DEFAULT '',
    context_json   TEXT DEFAULT '{}',
    UNIQUE(participant_id, domain, decided_at, pattern_ref)
);
CREATE INDEX IF NOT EXISTS idx_cand_stratum
    ON candidates(participant_id, stratum, decided_at);

CREATE TABLE IF NOT EXISTS batches (
    batch_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    participant_id TEXT NOT NULL REFERENCES participants(participant_id),
    kind           TEXT NOT NULL,
    created_at     TEXT NOT NULL,
    token          TEXT NOT NULL UNIQUE,
    expires_at     TEXT NOT NULL,
    form_id        TEXT DEFAULT '',
    sent_at        TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS items (
    item_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    batch_id       INTEGER NOT NULL REFERENCES batches(batch_id),
    candidate_id   INTEGER NOT NULL REFERENCES candidates(candidate_id),
    stratum        TEXT NOT NULL,
    inclusion_prob REAL NOT NULL,
    position       INTEGER NOT NULL,
    is_gold        INTEGER NOT NULL DEFAULT 0,
    gold_expected  TEXT DEFAULT '',
    UNIQUE(batch_id, candidate_id)
);

CREATE TABLE IF NOT EXISTS responses (
    response_id  INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id      INTEGER NOT NULL UNIQUE REFERENCES items(item_id),
    welcome      TEXT DEFAULT '',
    wanted       TEXT DEFAULT '',
    did_act      TEXT DEFAULT '',
    answered_at  TEXT DEFAULT '',
    latency_ms   INTEGER DEFAULT 0,
    raw_json     TEXT DEFAULT '{}'
);
"""


def init_db(path: str | None = None) -> None:
    with get_db(path) as conn:
        conn.executescript(DDL)


def utc_now_iso() -> str:
    return datetime.now(UTC).isoformat()


# ---------------------------------------------------------------------------
# Writers
# ---------------------------------------------------------------------------
def upsert_participant(p: Participant, path: str | None = None) -> None:
    with get_db(path) as conn:
        conn.execute(
            """INSERT INTO participants(participant_id, consented_at, timezone, status, notes)
               VALUES (?,?,?,?,?)
               ON CONFLICT(participant_id) DO UPDATE SET
                   timezone=excluded.timezone, status=excluded.status, notes=excluded.notes""",
            (p.participant_id, p.consented_at, p.timezone, p.status, p.notes),
        )


def insert_candidate(c: Candidate, path: str | None = None) -> int | None:
    """Idempotent on (participant, domain, tick, pattern) so a re-run of the
    shadow pass cannot silently duplicate the sampling frame."""
    with get_db(path) as conn:
        cur = conn.execute(
            """INSERT OR IGNORE INTO candidates
               (participant_id, domain, decided_at, stratum, fired_prod, reason,
                confidence, threshold, pattern_ref, context_json)
               VALUES (?,?,?,?,?,?,?,?,?,?)""",
            (c.participant_id, c.domain, c.decided_at, c.stratum, int(c.fired_prod),
             c.reason, c.confidence, c.threshold, c.pattern_ref, c.context_json),
        )
        return cur.lastrowid if cur.rowcount else None


def insert_batch(b: Batch, path: str | None = None) -> int:
    with get_db(path) as conn:
        cur = conn.execute(
            """INSERT INTO batches(participant_id, kind, created_at, token, expires_at,
                                   form_id, sent_at)
               VALUES (?,?,?,?,?,?,?)""",
            (b.participant_id, b.kind, b.created_at, b.token, b.expires_at,
             b.form_id, b.sent_at),
        )
        return int(cur.lastrowid)


def insert_items(items: list[Item], path: str | None = None) -> list[Item]:
    """Insert and **populate `item_id` on each dataclass**, returning them.

    Deliberately one INSERT per row rather than `executemany`: executemany cannot
    report per-row `lastrowid`, so the caller would be left holding Items with
    `item_id=None`, and the item id is what the form carries and what a response
    is keyed by. Batches are at most a dozen rows, so the cost is irrelevant and
    the correctness is not.

    On a duplicate (batch, candidate) the row is left alone and the existing id is
    read back, keeping the function idempotent.
    """
    with get_db(path) as conn:
        for i in items:
            cur = conn.execute(
                """INSERT OR IGNORE INTO items
                   (batch_id, candidate_id, stratum, inclusion_prob, position,
                    is_gold, gold_expected)
                   VALUES (?,?,?,?,?,?,?)""",
                (i.batch_id, i.candidate_id, i.stratum, i.inclusion_prob,
                 i.position, int(i.is_gold), i.gold_expected),
            )
            if cur.rowcount:
                i.item_id = int(cur.lastrowid)
            else:
                row = conn.execute(
                    "SELECT item_id FROM items WHERE batch_id=? AND candidate_id=?",
                    (i.batch_id, i.candidate_id),
                ).fetchone()
                i.item_id = int(row["item_id"]) if row else None
    return items


def upsert_response(r: Response, path: str | None = None) -> None:
    """One response per item. A resubmitted form overwrites, so the pipeline is
    safe to replay, the alternative (append) would double-count a label."""
    with get_db(path) as conn:
        conn.execute(
            """INSERT INTO responses(item_id, welcome, wanted, did_act,
                                     answered_at, latency_ms, raw_json)
               VALUES (?,?,?,?,?,?,?)
               ON CONFLICT(item_id) DO UPDATE SET
                   welcome=excluded.welcome, wanted=excluded.wanted,
                   did_act=excluded.did_act, answered_at=excluded.answered_at,
                   latency_ms=excluded.latency_ms, raw_json=excluded.raw_json""",
            (r.item_id, r.welcome, r.wanted, r.did_act, r.answered_at,
             r.latency_ms, r.raw_json),
        )


# ---------------------------------------------------------------------------
# Readers
# ---------------------------------------------------------------------------
def stratum_counts(participant_id: str, path: str | None = None) -> dict[str, int]:
    """Population size per stratum, the denominator of the inclusion probability."""
    with get_db(path) as conn:
        rows = conn.execute(
            "SELECT stratum, COUNT(*) c FROM candidates WHERE participant_id=? GROUP BY stratum",
            (participant_id,),
        ).fetchall()
    return {r["stratum"]: r["c"] for r in rows}


def candidates_in_stratum(
    participant_id: str, stratum: str, path: str | None = None
) -> list[dict[str, Any]]:
    with get_db(path) as conn:
        rows = conn.execute(
            "SELECT * FROM candidates WHERE participant_id=? AND stratum=? ORDER BY candidate_id",
            (participant_id, stratum),
        ).fetchall()
    return [dict(r) for r in rows]


def labelled_rows(path: str | None = None) -> list[dict[str, Any]]:
    """Everything needed for weighted estimation, in one join."""
    with get_db(path) as conn:
        rows = conn.execute(
            """SELECT c.candidate_id, c.participant_id, c.domain, c.decided_at,
                      c.stratum, c.fired_prod, c.reason, c.confidence, c.threshold,
                      c.pattern_ref, c.context_json,
                      i.item_id, i.inclusion_prob, i.position, i.is_gold, i.gold_expected,
                      b.batch_id, b.kind,
                      r.welcome, r.wanted, r.did_act, r.latency_ms, r.answered_at
               FROM items i
               JOIN candidates c ON c.candidate_id = i.candidate_id
               JOIN batches    b ON b.batch_id     = i.batch_id
               LEFT JOIN responses r ON r.item_id  = i.item_id
               ORDER BY b.batch_id, i.position"""
        ).fetchall()
    return [dict(r) for r in rows]
